// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNBBhyBv_sJNskh6NxaWMlLoPCzzOpy8',
    appId: '1:486295383601:web:2ac1272b4e72339d65af10',
    messagingSenderId: '486295383601',
    projectId: 'app-inventario-f69eb',
    authDomain: 'app-inventario-f69eb.firebaseapp.com',
    storageBucket: 'app-inventario-f69eb.firebasestorage.app',
    measurementId: 'G-JPLQXJ00S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMYac3usu3fFCswzO3esBPFbZJDON-CXw',
    appId: '1:486295383601:android:08d0708c2a9c984e65af10',
    messagingSenderId: '486295383601',
    projectId: 'app-inventario-f69eb',
    storageBucket: 'app-inventario-f69eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Ao8WFeGplp4FcVLd0K4OdXbQ8H7Ng5U',
    appId: '1:486295383601:ios:486026b4299676dc65af10',
    messagingSenderId: '486295383601',
    projectId: 'app-inventario-f69eb',
    storageBucket: 'app-inventario-f69eb.firebasestorage.app',
    iosBundleId: 'com.example.gestionDeInventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Ao8WFeGplp4FcVLd0K4OdXbQ8H7Ng5U',
    appId: '1:486295383601:ios:486026b4299676dc65af10',
    messagingSenderId: '486295383601',
    projectId: 'app-inventario-f69eb',
    storageBucket: 'app-inventario-f69eb.firebasestorage.app',
    iosBundleId: 'com.example.gestionDeInventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtNBBhyBv_sJNskh6NxaWMlLoPCzzOpy8',
    appId: '1:486295383601:web:aa0db1c59124958765af10',
    messagingSenderId: '486295383601',
    projectId: 'app-inventario-f69eb',
    authDomain: 'app-inventario-f69eb.firebaseapp.com',
    storageBucket: 'app-inventario-f69eb.firebasestorage.app',
    measurementId: 'G-ZVKZD0P254',
  );
}
